[package]
name = "076c/graphy"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rojoSrc/*", "rokit.toml", "default.project.json", ".gitignore"]

[dependencies]
